// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform. '
          'Run the FlutterFire CLI to add support.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASpdNZ9JftTWUUq1V3MIdLyjfDv_fqNX4',
    appId: '1:466628980317:android:5236109fe30f0a372de7b4',
    messagingSenderId: '466628980317',
    projectId: 'rota-escolar-6085e',
    storageBucket: 'rota-escolar-6085e.firebasestorage.app',
  );
}
